{
  "name": "@workspace/api-server",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "set NODE_ENV=development&& pnpm run build && pnpm run start",
    "build": "node ./build.mjs",
    "start": "node --env-file=.env --enable-source-maps ./dist/index.mjs",
    "typecheck": "tsc -p tsconfig.json --noEmit"
  },
  "dependencies": {
    "@google-cloud/storage": "^7.19.0",
    "@microsoft/microsoft-graph-client": "3.0.7",
    "@workspace/api-zod": "workspace:*",
    "@workspace/db": "workspace:*",
    "bcryptjs": "^3.0.3",
    "compression": "^1.8.1",
    "cookie-parser": "^1.4.7",
    "cors": "^2",
    "drizzle-orm": "catalog:",
    "express": "^5",
    "google-auth-library": "^10.6.2",
    "jsonwebtoken": "^9.0.3",
    "multer": "^2.1.1",
    "pdfkit": "^0.18.0",
    "pino": "^9",
    "pino-http": "^10",
    "sharp": "^0.34.5",
    "uuid": "^13.0.0",
    "web-push": "^3.6.7",
    "xlsx": "0.18.5"
  },
  "devDependencies": {
    "@types/bcryptjs": "^3.0.0",
    "@types/compression": "^1.8.1",
    "@types/cookie-parser": "^1.4.10",
    "@types/cors": "^2.8.19",
    "@types/express": "^5.0.6",
    "@types/jsonwebtoken": "^9.0.10",
    "@types/multer": "^2.1.0",
    "@types/node": "catalog:",
    "@types/pdfkit": "^0.17.5",
    "@types/uuid": "^11.0.0",
    "@types/web-push": "^3.6.4",
    "esbuild": "^0.27.3",
    "esbuild-plugin-pino": "^2.3.3",
    "pino-pretty": "^13",
    "thread-stream": "3.1.0"
  }
}
