/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */

export interface ActiveAttendanceMember {
  recordId: number;
  userId: number;
  fullName: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  userRole?: string | null;
  checkedInAt: Date;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  accuracyMeters?: number | null;
  /** @nullable */
  distanceMeters?: number | null;
  outOfRange: boolean;
  /** @nullable */
  selfieUrl?: string | null;
  /** @nullable */
  notes?: string | null;
}
