/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */
import type { AttendanceReportSessionStatus } from "./attendanceReportSessionStatus";

export interface AttendanceReportSession {
  checkInRecordId: number;
  /** @nullable */
  checkOutRecordId?: number | null;
  checkInAt: Date;
  /** @nullable */
  checkOutAt?: Date | null;
  /** @nullable */
  durationMinutes?: number | null;
  status: AttendanceReportSessionStatus;
}
