/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */

export type AttendanceRecordWithUserType =
  (typeof AttendanceRecordWithUserType)[keyof typeof AttendanceRecordWithUserType];

export const AttendanceRecordWithUserType = {
  check_in: "check_in",
  check_out: "check_out",
} as const;
