/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from "./activity";
import type { Project } from "./project";
import type { ProjectSummary } from "./projectSummary";
import type { Report } from "./report";

export interface OwnerProjectView {
  project: Project;
  activities: Activity[];
  reports: Report[];
  summary: ProjectSummary;
}
