/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */
import type { CreateBackup200Stats } from "./createBackup200Stats";

export type CreateBackup200 = {
  success?: boolean;
  filename?: string;
  size?: number;
  createdAt?: string;
  stats?: CreateBackup200Stats;
};
