/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */

export type DashboardSummaryAllProjectsItem = {
  id?: number;
  name?: string;
  overallProgress?: number;
  plannedProgress?: number;
  status?: string;
  daysRemaining?: number;
  /** @nullable */
  ownerEntity?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  expectedEndDate?: string | null;
  noSchedule?: boolean;
  /** Days passed after expectedEndDate while progress < 100% */
  overrunDays?: number;
};
