/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */
import type { EmployeeAttendanceDay } from "./employeeAttendanceDay";
import type { EmployeeAttendanceReportEmployee } from "./employeeAttendanceReportEmployee";
import type { EmployeeAttendanceReportProject } from "./employeeAttendanceReportProject";
import type { EmployeeAttendanceReportSummary } from "./employeeAttendanceReportSummary";

export interface EmployeeAttendanceReport {
  project: EmployeeAttendanceReportProject;
  employee: EmployeeAttendanceReportEmployee;
  /** @nullable */
  dateFrom?: Date | null;
  /** @nullable */
  dateTo?: Date | null;
  autoCloseHours: number;
  longDayHours: number;
  days: EmployeeAttendanceDay[];
  summary: EmployeeAttendanceReportSummary;
}
