/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */

export type DeviationTimelineSuspensionsBreakdownItemType =
  (typeof DeviationTimelineSuspensionsBreakdownItemType)[keyof typeof DeviationTimelineSuspensionsBreakdownItemType];

export const DeviationTimelineSuspensionsBreakdownItemType = {
  official_holiday: "official_holiday",
  force_majeure: "force_majeure",
  contractor_delay: "contractor_delay",
} as const;
