/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Engineering Supervision System
 * OpenAPI spec version: 0.1.0
 */
import type { AttendanceReportSession } from "./attendanceReportSession";
import type { EmployeeAttendanceDayFlags } from "./employeeAttendanceDayFlags";

export interface EmployeeAttendanceDay {
  date: Date;
  sessions: AttendanceReportSession[];
  totalMinutes: number;
  flags: EmployeeAttendanceDayFlags;
}
