import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import projectsRouter from "./projects";
import activitiesRouter from "./activities";
import reportsRouter from "./reports";
import filesRouter from "./files";
import usersRouter from "./users";
import ownerRouter from "./owner";
import dashboardRouter from "./dashboard";
import pdfRouter from "./pdf";
import extensionsRouter from "./extensions";
import suspensionsRouter from "./suspensions";
import companiesRouter from "./companies";
import projectMembersRouter from "./project-members";
import auditLogRouter from "./audit-log";
import activityGroupsRouter from "./activity-groups";
import setupRouter from "./setup";
import testResultsRouter from "./test-results";
import formsRouter from "./forms";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(projectMembersRouter);
router.use(activitiesRouter);
router.use(extensionsRouter);
router.use(suspensionsRouter);
router.use(pdfRouter);
router.use(reportsRouter);
router.use(filesRouter);
router.use(usersRouter);
router.use(ownerRouter);
router.use(dashboardRouter);
router.use(companiesRouter);
router.use(auditLogRouter);
router.use(activityGroupsRouter);
router.use(setupRouter);
router.use(testResultsRouter);
router.use(formsRouter);
router.use(backupRouter);

export default router;
